name: ci

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Login to HSDP Docker registry
        uses: docker/login-action@v2
        with:
          registry: docker.na1.hsdp.io
          username: ${{ secrets.HSDP_DOCKER_USERNAME }}
          password: ${{ secrets.HSDP_DOCKER_PASSWORD }}
      - uses: actions/checkout@v3
      -
        name: Build and push sd
        uses: docker/build-push-action@v4
        with:
          context: ./docker
          file: ./docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: philipslabs/cf-redis-exporter,docker.na1.hsdp.io/philipslabs/cf-redis-exporter
          cache-from: type=registry,ref=philipslabs/cf-redis-exporter:latest
          cache-to: type=inline